version: '3'

services:
  momentumx-app:
    container_name: momentumx-server
    env_file: docker.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:7000
    networks:
      - momentumx-network
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '7000:27017'
    networks:
      - momentumx-network

networks:
  momentumx-network:
    driver: bridge
